name: hive_flutter
description: Extension for Hive. Makes it easier to use Hive in Flutter apps.
version: 0.4.0-nullsafety.0
homepage: https://github.com/hivedb/hive/tree/master/hive_flutter
documentation: https://docs.hivedb.dev/

environment:
  sdk: '>=2.12.0-259.8.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  hive: ^1.6.0-nullsafety.0
  path_provider: ^2.0.0-nullsafety
  path: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ">=1.8.0 <2.0.0"
  mockito: ^5.0.0-nullsafety.5
  build_runner: ^1.10.0